export const reducerCases={
    SET_TOKEN:'SET-TOKEN',
    SET_PLAYLISTS:'SET_PLAYLISTS',
    SET_USER:'SET_USER',
    SET_SELECTED_PLAYLIST:"SET_SELECTED_PLAYLIST",
    SET_PLAYING:"SET_PLAYING",
    SET_PLAYER_STATE:"SET_PLAYER_STATE"
}